### ISSUE TITLE
STP or RSTP

### ISSUE THREAD

**Issue by leejbarker82** [IngmarStein/unifi-sonos-doc#11]
> Multicast and Broadcast Control: off
Settings -> Wireless Networks -> $YOUR_NETWORK
Block LAN to WLAN multicast and broadcast data (Classic UI): off
Settings -> Wireless Networks -> $YOUR_NETWORK

Been added to the new UI - The multicast / broadcast control does the same thing

**Comment by IngmarStein** [comment]
I guess it's time to remove "Block LAN to WLAN multicast and broadcast data" setting from the doc. I meant to say: if you enabled this setting in the Classic UI, better turn it off if you have Sonos devices on that network.

**Comment by leejbarker82** [comment]
`Block LAN to WLAN multicast and broadcast data (Classic UI): off
Settings -> Wireless Networks -> $YOUR_NETWORK`

I'd say just remove this bit...

Awesome work by the way. I noticed Unifi have started making vlans possible for audio equipment with some presets. Wish they'd sort this once and for all with a Sonos one!

Also, realised my title makes no sense, I was going to ask a different question but figured it out myself but forgot to change it.

**Comment by IngmarStein** [comment]
Updated!

And yes, the title confused me a bit :)

I think the fix really should be on the Sonos side. They should fix their STP implementation or get rid of it completely.

**Comment by leejbarker82** [comment]
True... It's outdated now.
