### ISSUE TITLE
Probleme mit Sonos und Unify

### ISSUE THREAD

**Issue by feron81** [IngmarStein/unifi-sonos-doc#4]
Ich habe seit ein paar Tagen vermehrt Netzwerkprobleme mit Sonos und Unify. Kannst du mich unterstützen bezüglich den optimalen Settings?

**Comment by IngmarStein** [comment]
Hi,

have you already posted about your problems in the [UniFi](http://community.ui.com) and/or [Sonos](https://de.community.sonos.com) communities?

**Comment by feron81** [comment]
Thank you for your informations. Yes, I posted this in different communities. I think I have now the problem. The problem are the WLAN channels.

**Comment by IngmarStein** [comment]
Ok, great. This doc is about operating Sonos speakers in a wired UniFi network, so your WiFi issue is probably unrelated to the problem discussed here.
