### ISSUE TITLE
Adjusting "Minimum Data Rate Control" really helps with WiFi access

### ISSUE THREAD

**Issue by johanforssell** [IngmarStein/unifi-sonos-doc#6]
I have all my speakers connected via WiFi. It's a mix of old and new models.

After reading https://simonhackett.com/2022/01/14/fixing-sonos-constant-disappearances-from-a-ubiquiti-unifi-wifi-network/ I lowered the "Minimum Data Rate Control" for the 2.4 GHz network to the minimum 1 Mbps. 

The app will now find the speakers much faster. 1 second for the overview screen to list all the speakers and an additional 1 second for it to list what's currently playing everywhere. 

It used to be 5s and then 10 or more seconds. Sometimes it could not get the currently playing at all.

![Screenshot 2024-01-03 at 08 28 41](https://github.com/IngmarStein/unifi-sonos-doc/assets/133804877/6dec5c52-53be-4378-a80b-b9bd4b8bc902)

(Network 8.0.24)

**Comment by johanforssell** [comment]
Perhaps you could add a section on WiFi issues as well - I keep coming back to this resource as I fiddle with my networking gear and I would like it to be comprehensive :-)

**Comment by IngmarStein** [comment]
Thanks for the suggestion. Lowering the minimum data rate for older devices sounds like a general advice and is not necessarily specific to Sonos. Modern Sonos devices (e.g. Arc, Amp, Five, Move 2, Era) work just find in my environment with 2.4 GHz and 5 GHz set to minimum 24 MBps. By lowering this setting, you prioritize compatibility over performance and that's exactly what the description of the setting says.
The "auto-optimize" mode referenced in the blog post doesn't exist anymore in recent UniFi Network application releases, afaik.
